"""
SIGMA Guardrails.
Mandatory output guardrails for regulatory compliance.
"""

DISCLAIMER_TEXT = (
    "⚠️ DISCLAIMER: This alert is generated by an AI system for informational purposes only. "
    "It does not constitute licensed financial advice under SEBI/PMLA regulations. "
    "Past signal performance does not guarantee future results. "
    "All investment decisions are the sole responsibility of the investor. "
    "Consult a SEBI-registered investment advisor before acting."
)

FORBIDDEN_PHRASES = [
    "will go up",
    "will go down",
    "guaranteed",
    "certain to",
    "definitely",
    "100%",
    "sure to",
    "cannot fail",
    "risk-free",
    "no risk",
]


def validate_alert_guardrails(alert) -> list[str]:
    """
    Validate alert against guardrails.

    Args:
        alert: FinalAlert to validate.

    Returns:
        List of validation errors (empty if valid).
    """
    errors = []

    # 1. Disclaimer must not be empty and must contain "DISCLAIMER"
    if not alert.disclaimer:
        errors.append("Missing disclaimer")
    elif "DISCLAIMER" not in alert.disclaimer:
        errors.append("Disclaimer must contain 'DISCLAIMER'")

    # 2. Check for forbidden phrases
    text_to_check = f"{alert.recommended_action} {alert.headline} {alert.signal_summary}"
    text_lower = text_to_check.lower()

    for phrase in FORBIDDEN_PHRASES:
        if phrase.lower() in text_lower:
            errors.append(f"Forbidden phrase found: '{phrase}'")

    # 3. Headline length
    if len(alert.headline) > 120:
        errors.append(f"Headline too long: {len(alert.headline)} chars (max 120)")

    # 4. Sources must not be empty
    if not alert.sources:
        errors.append("Sources list cannot be empty")

    # 5. Confidence score range
    if not (0.0 <= alert.confidence_score <= 1.0):
        errors.append(f"Invalid confidence score: {alert.confidence_score}")

    return errors


def ensure_disclaimer(text: str | None) -> str:
    """Ensure a valid disclaimer is present."""
    if text and "DISCLAIMER" in text:
        return text
    return DISCLAIMER_TEXT


def sanitize_recommendation(text: str) -> str:
    """Remove forbidden phrases from recommendation text."""
    result = text
    for phrase in FORBIDDEN_PHRASES:
        # Case-insensitive replacement
        import re
        pattern = re.compile(re.escape(phrase), re.IGNORECASE)
        result = pattern.sub("may", result)
    return result
